version: '3.3'
services:
  nginx:
    image: "test/nginx:1.0"
    container_name: nginx
    networks:
     - nginx
    ports:
     - 80:80
     - 443:443
    volumes:
     - "webpage:/var/www/html"
     - "certs:/etc/letsencrypt:ro"
    depends_on:
     - php
    environment:
#     - radarr=yes
#     - jackett=yes
#     - deluge=yes
#     - portainer=yes
#     - sonarr=yes
#     - plexpy=yes
     - domain="<domain>"
  php:
    image: "test/php:1.0"
    container_name: php
    networks:
     - nginx
    volumes:
     - "webpage:/var/www/html"
     - "database:/var/database"
networks:
  nginx:
      external: true
volumes:
  webpage:
      external: true
  database:
      external: true
  certs:
      external: true
